// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeMintInstruction {
  static encode(message: InitializeMintInstruction, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.decimals);

    writer.uint32(18);
    writer.string(message.mintAuthority);

    writer.uint32(26);
    writer.string(message.freezeAuthority);
  }

  static decode(reader: Reader, length: i32): InitializeMintInstruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeMintInstruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.decimals = reader.uint32();
          break;

        case 2:
          message.mintAuthority = reader.string();
          break;

        case 3:
          message.freezeAuthority = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  decimals: u32;
  mintAuthority: string;
  freezeAuthority: string;

  constructor(
    decimals: u32 = 0,
    mintAuthority: string = "",
    freezeAuthority: string = ""
  ) {
    this.decimals = decimals;
    this.mintAuthority = mintAuthority;
    this.freezeAuthority = freezeAuthority;
  }
}
