// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeMintAccounts {
  static encode(message: InitializeMintAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.mint);
  }

  static decode(reader: Reader, length: i32): InitializeMintAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeMintAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.mint = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  mint: string;

  constructor(mint: string = "") {
    this.mint = mint;
  }
}
