// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeMultisigAccounts {
  static encode(message: InitializeMultisigAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    const signers = message.signers;
    if (signers.length !== 0) {
      for (let i: i32 = 0; i < signers.length; ++i) {
        writer.uint32(18);
        writer.string(signers[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): InitializeMultisigAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeMultisigAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.signers.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  signers: Array<string>;

  constructor(account: string = "", signers: Array<string> = []) {
    this.account = account;
    this.signers = signers;
  }
}
