// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeMultisigInstruction {
  static encode(message: InitializeMultisigInstruction, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.signatureCountThreshold);
  }

  static decode(reader: Reader, length: i32): InitializeMultisigInstruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeMultisigInstruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signatureCountThreshold = reader.uint32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signatureCountThreshold: u32;

  constructor(signatureCountThreshold: u32 = 0) {
    this.signatureCountThreshold = signatureCountThreshold;
  }
}
