[workspace]
members = ["substreams/solana"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
substreams = "0.5"
substreams-solana = "0.13"
substreams-database-change = "1.3"
substreams-solana-program-instructions = "0.1"
