// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeAccountAccounts {
  static encode(message: InitializeAccountAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    writer.uint32(18);
    writer.string(message.mint);

    writer.uint32(26);
    writer.string(message.owner);
  }

  static decode(reader: Reader, length: i32): InitializeAccountAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeAccountAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.mint = reader.string();
          break;

        case 3:
          message.owner = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  mint: string;
  owner: string;

  constructor(account: string = "", mint: string = "", owner: string = "") {
    this.account = account;
    this.mint = mint;
    this.owner = owner;
  }
}
