// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

export enum AuthorityType {
  AuthorityNull = 0,
  AuthorityMintTokens = 1,
  AuthorityFreezeAccount = 2,
  AuthorityAccountOwner = 3,
  AuthorityCloseAccount = 4,
}
