// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializeImmutableOwnerAccounts {
  static encode(
    message: InitializeImmutableOwnerAccounts,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.account);
  }

  static decode(reader: Reader, length: i32): InitializeImmutableOwnerAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeImmutableOwnerAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;

  constructor(account: string = "") {
    this.account = account;
  }
}
