// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { ApproveInstruction } from "./Approve/ApproveInstruction";
import { ApproveAccounts } from "./Approve/ApproveAccounts";

export class Approve {
  static encode(message: Approve, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      ApproveInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      ApproveAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Approve {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Approve();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = ApproveInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = ApproveAccounts.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: ApproveInstruction | null;
  accounts: ApproveAccounts | null;

  constructor(
    instruction: ApproveInstruction | null = null,
    accounts: ApproveAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
