// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { FreezeAccountInstruction } from "./FreezeAccount/FreezeAccountInstruction";
import { FreezeAccountAccounts } from "./FreezeAccount/FreezeAccountAccounts";

export class FreezeAccount {
  static encode(message: FreezeAccount, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      FreezeAccountInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      FreezeAccountAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): FreezeAccount {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FreezeAccount();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = FreezeAccountInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = FreezeAccountAccounts.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: FreezeAccountInstruction | null;
  accounts: FreezeAccountAccounts | null;

  constructor(
    instruction: FreezeAccountInstruction | null = null,
    accounts: FreezeAccountAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
