// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { InitializeImmutableOwnerInstruction } from "./InitializeImmutableOwner/InitializeImmutableOwnerInstruction";
import { InitializeImmutableOwnerAccounts } from "./InitializeImmutableOwner/InitializeImmutableOwnerAccounts";

export class InitializeImmutableOwner {
  static encode(message: InitializeImmutableOwner, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      InitializeImmutableOwnerInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      InitializeImmutableOwnerAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): InitializeImmutableOwner {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializeImmutableOwner();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = InitializeImmutableOwnerInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = InitializeImmutableOwnerAccounts.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: InitializeImmutableOwnerInstruction | null;
  accounts: InitializeImmutableOwnerAccounts | null;

  constructor(
    instruction: InitializeImmutableOwnerInstruction | null = null,
    accounts: InitializeImmutableOwnerAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
