// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { RevokeInstruction } from "./Revoke/RevokeInstruction";
import { RevokeAccounts } from "./Revoke/RevokeAccounts";

export class Revoke {
  static encode(message: Revoke, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      RevokeInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      RevokeAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Revoke {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Revoke();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = RevokeInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = RevokeAccounts.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: RevokeInstruction | null;
  accounts: RevokeAccounts | null;

  constructor(
    instruction: RevokeInstruction | null = null,
    accounts: RevokeAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
