// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class SingleSignature {
  static encode(message: SingleSignature, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): SingleSignature {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SingleSignature();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signer: string;

  constructor(signer: string = "") {
    this.signer = signer;
  }
}
