// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { SyncNativeInstruction } from "./SyncNative/SyncNativeInstruction";
import { SyncNativeAccounts } from "./SyncNative/SyncNativeAccounts";

export class SyncNative {
  static encode(message: SyncNative, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      SyncNativeInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      SyncNativeAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SyncNative {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SyncNative();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = SyncNativeInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = SyncNativeAccounts.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: SyncNativeInstruction | null;
  accounts: SyncNativeAccounts | null;

  constructor(
    instruction: SyncNativeInstruction | null = null,
    accounts: SyncNativeAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
