// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { ThawAccountInstruction } from "./ThawAccount/ThawAccountInstruction";
import { ThawAccountAccounts } from "./ThawAccount/ThawAccountAccounts";

export class ThawAccount {
  static encode(message: ThawAccount, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      ThawAccountInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      ThawAccountAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ThawAccount {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ThawAccount();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = ThawAccountInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = ThawAccountAccounts.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: ThawAccountInstruction | null;
  accounts: ThawAccountAccounts | null;

  constructor(
    instruction: ThawAccountInstruction | null = null,
    accounts: ThawAccountAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
