// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { TransferInstruction } from "./Transfer/TransferInstruction";
import { TransferAccounts } from "./Transfer/TransferAccounts";

export class Transfer {
  static encode(message: Transfer, writer: Writer): void {
    const instruction = message.instruction;
    if (instruction !== null) {
      writer.uint32(10);
      writer.fork();
      TransferInstruction.encode(instruction, writer);
      writer.ldelim();
    }

    const accounts = message.accounts;
    if (accounts !== null) {
      writer.uint32(18);
      writer.fork();
      TransferAccounts.encode(accounts, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Transfer {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Transfer();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instruction = TransferInstruction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.accounts = TransferAccounts.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instruction: TransferInstruction | null;
  accounts: TransferAccounts | null;

  constructor(
    instruction: TransferInstruction | null = null,
    accounts: TransferAccounts | null = null
  ) {
    this.instruction = instruction;
    this.accounts = accounts;
  }
}
