// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class SyncNativeAccounts {
  static encode(message: SyncNativeAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.nativeTokenAccount);
  }

  static decode(reader: Reader, length: i32): SyncNativeAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SyncNativeAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.nativeTokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  nativeTokenAccount: string;

  constructor(nativeTokenAccount: string = "") {
    this.nativeTokenAccount = nativeTokenAccount;
  }
}
