// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Signer } from "../Signer";

export class MintToAccounts {
  static encode(message: MintToAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.mint);

    writer.uint32(18);
    writer.string(message.destination);

    const mintAuthority = message.mintAuthority;
    if (mintAuthority !== null) {
      writer.uint32(26);
      writer.fork();
      Signer.encode(mintAuthority, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MintToAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MintToAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.mint = reader.string();
          break;

        case 2:
          message.destination = reader.string();
          break;

        case 3:
          message.mintAuthority = Signer.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  mint: string;
  destination: string;
  mintAuthority: Signer | null;

  constructor(
    mint: string = "",
    destination: string = "",
    mintAuthority: Signer | null = null
  ) {
    this.mint = mint;
    this.destination = destination;
    this.mintAuthority = mintAuthority;
  }
}
