// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Signer } from "../Signer";

export class ThawAccountAccounts {
  static encode(message: ThawAccountAccounts, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.account);

    writer.uint32(18);
    writer.string(message.mint);

    const mintFreezeAuthority = message.mintFreezeAuthority;
    if (mintFreezeAuthority !== null) {
      writer.uint32(26);
      writer.fork();
      Signer.encode(mintFreezeAuthority, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ThawAccountAccounts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ThawAccountAccounts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.account = reader.string();
          break;

        case 2:
          message.mint = reader.string();
          break;

        case 3:
          message.mintFreezeAuthority = Signer.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  account: string;
  mint: string;
  mintFreezeAuthority: Signer | null;

  constructor(
    account: string = "",
    mint: string = "",
    mintFreezeAuthority: Signer | null = null
  ) {
    this.account = account;
    this.mint = mint;
    this.mintFreezeAuthority = mintFreezeAuthority;
  }
}
